version: '1.0'

services:
  nextjs:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
